apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: newspaper
  name: newspaper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newspaper
  template:
    metadata:
      labels:
        app: newspaper
    spec:
      containers:
      - image: kraktorist/news-backend:1.0
        name: news-backend
        env:
          - name: DATABASE_URL
            value: postgres://postgres:postgres@postgres:5432/news
        ports:
          - containerPort: 9000
      - image: kraktorist/news-frontend:1.1
        name: news-frontend
        ports:
          - containerPort: 80
        env:
          - name: BASE_URL
            value: http://newspaper:9000
---
