apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
       elasticsearch
  template:
    metadata:
      labels:
        elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:7.9.3
       - name: nginx-proxy
          image: nginx:1.19.5
          ports:
            - name: https
              containerPort: 9200
